### ISSUE TITLE
sixth sense

### ISSUE THREAD

**Issue by bharartwaj** [sixthsense/sixthsense#20]
System.NullReferenceException was unhandled
  Message=Object reference not set to an instance of an object.
  Source=WpfUserControl_Mail01
  StackTrace:
       at WpfUserControl_Mail01.UserControl1..ctor()
       at WUW01.WUW..ctor() in c:\Users\bharatwaj di matias\Downloads\Compressed\sixthsense-0.1beta\sixthsense-0.1beta\WUW01\WUW.cs:line 142
       at WUW01.Program.Main() in c:\Users\bharatwaj di matias\Downloads\Compressed\sixthsense-0.1beta\sixthsense-0.1beta\WUW01\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by vecdid** [comment]
bharartwaj ,

I have searched the current code for "WPF" and "mail" and I do not see this control anywhere, so I am not sure what is going on with your source, try and download from this site and see if you get the same error. If it continues, please do a search for "WPF" and let me know where you have this line of code for Mail01. Program.cs line 18 is where the application is run.

Have a great day!
James Campbell
MCP, MCSE, MCSA, Security +
