### ISSUE TITLE
WebCamLib.dll Error even after repeating the steps for 64 bit system Sixth Sense Code

### ISSUE THREAD

**Issue by himanshu7037** [sixthsense/sixthsense#24]
System.DllNotFoundException was unhandled
  Message=Unable to load DLL 'WebCamLib.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=TouchlessLib
  TypeName=""
  StackTrace:
       at TouchlessLib.NativeMethods.WebCamInitialize()
       at TouchlessLib.TouchlessMgr..ctor()
       at WUW01.WUW.WUW_Load(Object sender, EventArgs e) in C:\Users\Himanshu PC\Desktop\code\sixthsense-sixthsense-a921d10\WUW01\WUW.cs:line 586
       at System.Windows.Forms.Form.OnLoad(EventArgs e)
       at System.Windows.Forms.Form.OnCreateControl()
       at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       at System.Windows.Forms.Control.CreateControl()
       at System.Windows.Forms.Control.WmShowWindow(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
       at System.Windows.Forms.ContainerControl.WndProc(Message& m)
       at System.Windows.Forms.Form.WmShowWindow(Message& m)
       at System.Windows.Forms.Form.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
  InnerException:

**Comment by vecdid** [comment]
himanshu7037 ,

Good evening, what steps are you repeating?

Have a great day!
James Campbell
MCP, MCSE, MCSA, Security +
